insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000001', 'CLIENTES', 'GRUPOS DE CLIENTES','CREAR', 'SI', 'grupo_cliente', 'GCL', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000002', 'CLIENTES', 'CLIENTES','CREAR', 'SI', 'cliente', 'CLI', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000003', 'CLIENTES', 'CLIENTES','CREAR', 'NO', 'dependiente', 'DEP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000004', 'CLIENTES', 'CLIENTES','CREAR', 'NO', 'celular', 'CEL', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000005', 'CLIENTES', 'CLIENTES','CREAR', 'NO', 'celular_dependiente', 'CED', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000006', 'CLIENTES', 'CLIENTES','CREAR', 'NO', 'correo', 'COR', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000007', 'CLIENTES', 'CLIENTES','CREAR', 'NO', 'correo_dependiente', 'COD', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000008', 'CLIENTES', 'CLIENTES','CREAR', 'NO', 'telefono', 'TEL', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000009', 'CLIENTES', 'CLIENTES','CREAR', 'NO', 'telefono_dependiente', 'TED', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000010', 'CLIENTES', 'CLIENTES','CREAR', 'NO', 'tipo_contribuyente', 'TCO', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000011', 'CLIENTES', 'CLIENTES','CREAR', 'NO', 'retencion_cliente', 'RCL', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000012', 'CLIENTES', 'CLIENTES','CREAR', 'NO', 'tipo_identificacion', 'TID', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000013', 'CLIENTES', 'SEGMENTOS','CREAR', 'SI', 'segmento', 'SEG', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000014', 'CLIENTES', 'FORMAS DE PAGO','CREAR', 'SI', 'forma_pago', 'FPA', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000015', 'CLIENTES', 'ORIGEN DE INGRESOS','CREAR', 'SI', 'origen_ingreso', 'OIN', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000016', 'CLIENTES', 'PLAZOS DE CRÉDITO','CREAR', 'SI', 'plazo_credito', 'PCR', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000017', 'CLIENTES', 'CALIFICACIÓN DE CLIENTES','CREAR', 'SI', 'calificacion_cliente', 'CCL', 'ACTIVO', default, default);
--COMPRAS
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000018', 'COMPRAS', 'GRUPOS DE PROVEEDORES','CREAR', 'SI', 'grupo_proveedor', 'GPR', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000019', 'COMPRAS', 'PROVEEDORES','CREAR', 'SI', 'proveedor', 'PRV', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000020', 'COMPRAS', 'PROVEEDORES','CREAR', 'NO', 'celular_proveedor', 'CEP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000021', 'COMPRAS', 'PROVEEDORES','CREAR', 'NO', 'correo_proveedor', 'COP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000022', 'COMPRAS', 'PROVEEDORES','CREAR', 'NO', 'telefono_proveedor', 'TEP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000023', 'COMPRAS', 'FACTURAS DE COMPRA','CREAR', 'SI', 'factura_compra', 'FCO', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000024', 'COMPRAS', 'FACTURAS DE COMPRA','CREAR', 'NO', 'factura_compra_linea', 'FCL', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000025', 'COMPRAS', 'NOTAS DE CRÉDITO COMPRA','CREAR', 'SI', 'nota_credito_compra', 'NCC', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000026', 'COMPRAS', 'NOTAS DE CRÉDITO COMPRA','CREAR', 'NO', 'nota_credito_compra_linea', 'NCCL', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000027', 'COMPRAS', 'NOTAS DE DÉBITO COMPRA','CREAR', 'SI', 'nota_debito_compra', 'NDC', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000028', 'COMPRAS', 'NOTAS DE DÉBITO COMPRA','CREAR', 'NO', 'nota_debito_compra_linea', 'NDCL', 'ACTIVO', default, default);
--VENTAS
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000029', 'VENTAS', 'FACTURAS','CREAR', 'SI', 'factura', 'FAC', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000030', 'VENTAS', 'NOTAS DE DÉBITO','CREAR', 'SI', 'nota_debito', 'ND', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000031', 'VENTAS', 'NOTAS DE DÉBITO','CREAR', 'NO', 'nota_debito_linea', 'NDL', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000032', 'VENTAS', 'NOTAS DE CRÉDITO','CREAR', 'SI', 'nota_credito', 'NC', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000033', 'VENTAS', 'NOTAS DE CRÉDITO','CREAR', 'NO', 'nota_credito_linea', 'NCL', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000034', 'VENTAS', 'PEDIDO','CREAR', 'SI', 'pedido', 'PED', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000035', 'VENTAS', 'PROFORMA','CREAR', 'SI', 'proforma', 'PRF', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000036', 'VENTAS', 'EGRESO','CREAR', 'SI', 'egreso', 'EGR', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000037', 'VENTAS', 'CIERRE DE CAJA','CREAR', 'SI', 'cierre_caja', 'CIC', 'ACTIVO', default, default);
--RECAUDACIÓN
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000038', 'VENTAS', 'RECAUDACIÓN','CREAR', 'NO', 'amortizacion', 'AMO', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000039', 'VENTAS', 'RECAUDACIÓN','CREAR', 'NO', 'cheque_vista', 'CHV', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000040', 'VENTAS', 'RECAUDACIÓN','CREAR', 'NO', 'cheque_posfechado', 'CHP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000041', 'VENTAS', 'RECAUDACIÓN','CREAR', 'NO', 'credito', 'CRE', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000042', 'VENTAS', 'RECAUDACIÓN','CREAR', 'NO', 'retencion', 'CTP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000043', 'VENTAS', 'RECAUDACIÓN','CREAR', 'NO', 'deposito', 'DEP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000044', 'VENTAS', 'RECAUDACIÓN','CREAR', 'NO', 'efectivo', 'EFE', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000045', 'VENTAS', 'RECAUDACIÓN','CREAR', 'NO', 'tarjeta_credito', 'TCR', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000046', 'VENTAS', 'RECAUDACIÓN','CREAR', 'NO', 'tarjeta_debito', 'TDE', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000047', 'VENTAS', 'RECAUDACIÓN','CREAR', 'NO', 'recaudacion', 'REC', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000048', 'VENTAS', 'RECAUDACIÓN','CREAR', 'NO', 'transferencia', 'TRF', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000049', 'VENTAS', 'RECAUDACIÓN','CREAR', 'NO', 'retencion_venta', 'RVE', 'ACTIVO', default, default);
--ENTREGA
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000050', 'VENTAS', 'ENTREGA','CREAR', 'NO', 'entrega', 'ENT', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000051', 'VENTAS', 'GUIAS DE REMISION','CREAR', 'SI', 'guia_remision', 'GRE', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000052', 'VENTAS', 'TRANSPORTISTAS','CREAR', 'SI', 'transportista', 'TRAN', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000053', 'VENTAS', 'VEHICULOS TRANSPORTES','CREAR', 'SI', 'vehiculo_transporte', 'VEH', 'ACTIVO', default, default);
--INVENTARIOS
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000054', 'INVENTARIOS', 'CATEGORÍA PRODUCTO','CREAR', 'NO', 'categoria_producto', 'CAP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000055', 'INVENTARIOS', 'GRUPOS DE PRODUCTOS','CREAR', 'SI', 'grupo_producto', 'GPR', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000056', 'INVENTARIOS', 'PRODUCTOS','CREAR', 'SI', 'producto', 'PRO', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000057', 'INVENTARIOS', 'PRECIO','CREAR', 'NO', 'precio', 'PRE', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000058', 'INVENTARIOS', 'PROVEEDORES DE PRODUCTOS','CREAR', 'NO', 'proveedor_producto', 'PRP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000059', 'INVENTARIOS', 'KARDEX','CREAR', 'SI', 'kardex', 'KAR', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000060', 'INVENTARIOS', 'PROMOCIONES','CREAR', 'SI', 'promocion', 'PRM', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000061', 'INVENTARIOS', 'BODEGAS','CREAR', 'SI', 'bodega', 'BOD', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000062', 'INVENTARIOS', 'BODEGAS','CREAR', 'NO', 'bodega_producto', 'BOP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000063', 'INVENTARIOS', 'TRANSFERENCIAS DE BODEGA','CREAR', 'NO', 'transferencia_bodega', 'TRB', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000064', 'INVENTARIOS', 'MEDIDAS','CREAR', 'SI', 'medida', 'MED', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000065', 'INVENTARIOS', 'EQUIVALENCIA DE MEDIDAS','CREAR', 'NO', 'equivalencia_medida', 'EQM', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000066', 'INVENTARIOS', 'TIPO GASTO','CREAR', 'NO', 'tipo_gasto', 'TIG', 'ACTIVO', default, default);
--CAJA BANCOS
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000067', 'CAJA BANCOS', 'CUENTAS PROPIAS','CREAR', 'SI', 'cuenta_propia', 'CTP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000068', 'CAJA BANCOS', 'BANCOS','CREAR', 'SI', 'banco', 'BAN', 'ACTIVO', default, default);
--CUENTAS X COBRAR
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000069', 'CUENTAS POR COBRAR', 'CUENTAS POR COBRAR','CREAR', 'NO', 'cuentas_cobrar', 'CXC', 'ACTIVO', default, default);
--CUENTAS X PAGAR
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000070', 'CUENTAS POR PAGAR', 'CUENTAS POR PAGAR','CREAR', 'NO', 'cuentas_pagar', 'CXP', 'ACTIVO', default, default);
--ACTIVOS FIJOS
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000071', 'ACTIVOS FIJOS', 'ACTIVOS FIJOS','CREAR', 'NO', 'activos_fijos', 'ACF', 'ACTIVO', default, default);
--PRODUCCIÓN
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000072', 'PRODUCCION', 'PRODUCCION','CREAR', 'NO', 'produccion', 'PDC', 'ACTIVO', default, default);
--CONTABILIDAD
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000073', 'CONTABILIDAD', 'CUENTAS CONTABLES','CREAR', 'SI', 'cuenta_contable', 'CTC', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000074', 'CONTABILIDAD', 'MOVIMIENTOS CONTABLES','CREAR', 'SI', 'movimiento_contable', 'MVC', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000075', 'CONTABILIDAD', 'AFECTACION CONTABLE','CREAR', 'NO', 'afectacion_contable', 'AFC', 'ACTIVO', default, default);
--TALENTO HUMANO
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000076', 'TALENTO HUMANO', 'TALENTO HUMANO','CREAR', 'NO', 'talento_humano', 'TTH', 'ACTIVO', default, default);
--FINANCIERO
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000077', 'FINANCIERO', 'FINANCIERO','CREAR', 'NO', 'financiero', 'FIN', 'ACTIVO', default, default);
--IMPORTACIÓN
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000078', 'IMPORTACION', 'IMPORTACION','CREAR', 'NO', 'importacion', 'IMT', 'ACTIVO', default, default);
--REPORTES
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000079', 'REPORTES', 'CLIENTE','CREAR', 'SI', '', 'REP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000080', 'REPORTES', 'COMPRAS','CREAR', 'SI', '', 'REP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000081', 'REPORTES', 'VENTAS','CREAR', 'SI', '', 'REP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000082', 'REPORTES', 'INVENTARIOS','CREAR', 'SI', '', 'REP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000083', 'REPORTES', 'CAJA BANCOS','CREAR', 'SI', '', 'REP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000084', 'REPORTES', 'CUENTAS POR COBRAR','CREAR', 'SI', '', 'REP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000085', 'REPORTES', 'CUENTAS POR PAGAR','CREAR', 'SI', '', 'REP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000086', 'REPORTES', 'ACTIVOS FIJOS','CREAR', 'SI', '', 'REP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000087', 'REPORTES', 'PRODUCCIÓN','CREAR', 'SI', '', 'REP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000088', 'REPORTES', 'CONTABILIDAD','CREAR', 'SI', '', 'REP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000089', 'REPORTES', 'TALENTO HUMANO','CREAR', 'SI', '', 'REP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000090', 'REPORTES', 'FINANCIERO','CREAR', 'SI', '', 'REP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000091', 'REPORTES', 'IMPORTACIÓN','CREAR', 'SI', '', 'REP', 'ACTIVO', default, default);
-- ACCESOS
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000092', 'ACCESOS', 'USUARIOS','CREAR', 'SI', 'usuario', 'USR', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000093', 'ACCESOS', 'EMPRESAS','CREAR', 'SI', 'empresa', 'EMP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000094', 'ACCESOS', 'ESTABLECIMIENTOS','CREAR', 'SI', 'establecimiento', 'EST', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000095', 'ACCESOS', 'ESTABLECIMIENTOS','CREAR', 'NO', 'celular_establecimiento', 'CEE', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000096', 'ACCESOS', 'ESTABLECIMIENTOS','CREAR', 'NO', 'correo_establecimiento', 'COE', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000097', 'ACCESOS', 'ESTABLECIMIENTOS','CREAR', 'NO', 'telefono_establecimiento', 'TEE', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000098', 'ACCESOS', 'ESTACIONES','CREAR', 'SI', 'estacion', 'ESN', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000099', 'ACCESOS', 'ESTACIÓN USUARIO','CREAR', 'NO', 'estacion_usuario', 'ESU', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000100', 'ACCESOS', 'PERFILES','CREAR', 'SI', 'perfil', 'PER', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000101', 'ACCESOS', 'PERMISOS','CREAR', 'SI', 'permiso', 'PRM', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000102', 'ACCESOS', 'SESION','CREAR', 'NO', 'sesion', 'SES', 'ACTIVO', default, default);
--CONFIGURACIÓN
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000103', 'CONFIGURACION', 'UBICACIÓN','CREAR', 'SI', 'ubicacion', 'UBI', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000104', 'CONFIGURACION', 'UBICACIÓN','CREAR', 'NO', 'direccion', 'DIR', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000105', 'CONFIGURACION', 'ESTADO CIVIL','CREAR', 'SI', 'estado_civil', 'ECV', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000106', 'CONFIGURACION', 'IMPUESTOS','CREAR', 'SI', 'impuesto', 'IMP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000107', 'CONFIGURACION', 'SECUENCIALES','CREAR', 'SI', 'secuencial', 'SEC', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000108', 'CONFIGURACION', 'TIPOS DE RETENCIÓN','CREAR', 'SI', 'tipo_retencion', 'TRE', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000109', 'CONFIGURACION', 'RÉGIMEN','CREAR', 'SI', 'regimen', 'REG', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000110', 'CONFIGURACION', 'IMPORTACIONES','CREAR', 'SI', '', 'IMP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000111', 'CONFIGURACION', 'EXPORTACIONES','CREAR', 'SI', '', 'EXP', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000112', 'CONFIGURACION', 'MENU','CREAR', 'NO', 'menu', 'MEN', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000113', 'CONFIGURACION', 'PARAMETROS','CREAR', 'NO', 'parametro', 'PAR', 'ACTIVO', default, default);
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000114', 'CONFIGURACION', 'GENERO','CREAR', 'NO', 'genero', 'GEN', 'ACTIVO', default, default);
--INDICADORES
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000115', 'INDICADORES', 'DASHBOARD','CREAR', 'SI', 'dashboard', 'DAS', 'ACTIVO', default, default);
--CONTROL
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000116', 'CONTROL', 'CONTROL','CREAR', 'NO', 'produccion', 'PDC', 'ACTIVO', default, default);
--AUDITORÍA
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000117', 'AUDITORIA', 'AUDITORIA','CREAR', 'NO', 'produccion', 'PDC', 'ACTIVO', default, default);
--TUTORIALES
insert into menu_opcion (id, codigo, modulo, opcion, operacion, menu, tabla, abreviatura, estado, fecha_creacion, fecha_actualizacion) values(default, 'MEN202305000118', 'TUTORIALES', 'TUTORIALES','CREAR', 'NO', 'produccion', 'PDC', 'ACTIVO', default, default);