CREATE TABLE banco(
   id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   codigo 	varchar,
   ruc	varchar,
   razon_social 	varchar,
   subsistema	varchar,
   calificacion	varchar,
   abreviatura	varchar,
   estado	varchar,
   fecha_creacion	timestamp without time zone NOT NULL, 
   fecha_actualizacion	timestamp without time zone NOT NULL,
   PRIMARY KEY (id)
);