CREATE TABLE cheque(
   id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   codigo 	varchar,
   numero varchar,
   tipo varchar,
   fecha timestamp without time zone,
   fecha_efectivizacion timestamp without time zone,
   valor double precision,
   estado varchar,
   banco_id bigint,
   factura_id bigint,
   fecha_creacion	timestamp without time zone NOT NULL default CURRENT_TIMESTAMP, 
   fecha_actualizacion	timestamp without time zone NOT NULL default CURRENT_TIMESTAMP,
   PRIMARY KEY (id)
);