CREATE TABLE cierre_caja(
   id       bigint IDENTITY NOT NULL,
   codigo 	varchar,
   fecha timestamp without time zone,
   billete100 double,
   billete50 double,
   billete20 double,
   billete10 double,
   billete5 double,
   billete2 double,
   billete1 double,
   moneda100 double,
   moneda50 double,
   moneda25 double,
   moneda10 double,
   moneda5 double,
   moneda1 double,
   total_billetes double,
   total_monedas double,
   total_caja double,
   estado varchar,
   fecha_creacion	timestamp without time zone NOT NULL, 
   fecha_actualizacion	timestamp without time zone NOT NULL,
   sesion_id bigint,
   empresa_id bigint,
   PRIMARY KEY (id)
);