CREATE TABLE dependiente(
   id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   codigo 	varchar,
   razon_social	varchar,
   direccion 	varchar,
   latitudgeo	double precision,
   longitudgeo double precision,
   estado	varchar,
   ubicacion_id bigint,
   cliente_id bigint,
   fecha_creacion	timestamp without time zone NOT NULL default CURRENT_TIMESTAMP, 
   fecha_actualizacion	timestamp without time zone NOT NULL default CURRENT_TIMESTAMP,
   PRIMARY KEY (id)
);