CREATE TABLE factura(
   id       bigint IDENTITY NOT NULL,
   codigo 	varchar,
   establecimiento varchar,
   punto_venta varchar,
   secuencial varchar,
   numero_comprobante varchar,
   codigo_numerico varchar,
   fecha timestamp without time zone,
   fecha_autorizacion timestamp without time zone,
   clave_acceso varchar,
   estado varchar,
   proceso_sri varchar,
   valor_descuento_total double,
   porcentaje_descuento_total double,
   valor_porcentaje_descuento_total double,
   valor_descuento_subtotal double,
   porcentaje_descuento_subtotal double,
   valor_porcentaje_descuento_subtotal double,
   subtotal double,
   descuento double,
   subtotal_gravado double,
   subtotal_no_gravado double,
   importe_iva double,
   total double,
   comentario varchar,
   fecha_creacion	timestamp without time zone NOT NULL, 
   fecha_actualizacion	timestamp without time zone NOT NULL,
   cliente_id bigint,
   sesion_id bigint,
   tipo_comprobante_id bigint,
   empresa_id bigint,
   total_recaudacion double,
   por_pagar double,
   efectivo double,
   cambio double,
   total_cheques double,
   total_depositos double,
   total_transferencias double,
   total_tarjetas_debitos double,
   total_tarjetas_creditos double,
   total_credito double,
   credito_id bigint,
   PRIMARY KEY (id)
);