CREATE TABLE factura_compra_linea(
   id       bigint IDENTITY NOT NULL,
   codigo 	varchar,
   posicion bigint,
   cantidad bigint,
   costo_unitario double,
   costo_distribuido double,
   costo_promedio double,
   valor_descuento_linea double,
   porcentaje_descuento_linea double,
   valor_porcentaje_descuento_linea double,
   valor_descuento_total_linea double,
   valor_porcentaje_descuento_total_linea double,
   subtotal_linea_sin_descuento double,
   subtotal_linea double,
   importe_iva_linea double,
   total_linea double,
   fecha_creacion	timestamp without time zone NOT NULL, 
   fecha_actualizacion	timestamp without time zone NOT NULL,
   impuesto_id bigint,
   producto_id bigint,
   bodega_id bigint,
   factura_compra_id bigint,
   PRIMARY KEY (id)
);