CREATE TABLE factura_compra(
   id       bigint IDENTITY NOT NULL,
   codigo 	varchar,
   establecimiento varchar,
   punto_venta varchar,
   secuencial varchar,
   numero_comprobante varchar,
   fecha timestamp without time zone,
   estado varchar,
   valor_distribuido_total double,
   valor_Descuento_total double,
   porcentaje_descuento_total double,
   valor_procentaje_descuento_total double,
   subtotal double,
   descuento double,
   subtotal_gravado_con_descuento double,
   subtotal_no_gravado_con_descuento double,
   importe_iva_total double,
   total double,
   comentario varchar,
   fecha_creacion	timestamp without time zone NOT NULL, 
   fecha_actualizacion	timestamp without time zone NOT NULL,
   proveedor_id bigint,
   sesion_id bigint,
   tipo_comprobante_id bigint,
   empresa_id bigint,
   PRIMARY KEY (id)
);