CREATE TABLE nd_cheque(
   id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   codigo 	varchar,
   numero varchar,
   tipo varchar,
   fecha timestamp without time zone,
   fecha_efectivizacion timestamp without time zone,
   valor double precision,
   fecha_creacion	timestamp without time zone NOT NULL, 
   fecha_actualizacion	timestamp without time zone NOT NULL,
   banco_id bigint,
   nota_debito_id bigint,
   PRIMARY KEY (id)
);