CREATE TABLE nota_credito_linea(
   id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   codigo 	varchar,
   cantidad_venta bigint,
   costo_unitario_venta double precision,
   cantidad bigint,
   costo_unitario double precision,
   subtotal_linea double precision,
   importe_iva_linea double precision,
   total_linea double precision,
   fecha_creacion	timestamp without time zone NOT NULL, 
   fecha_actualizacion	timestamp without time zone NOT NULL,
   impuesto_id bigint,
   precio_id bigint,
   producto_id bigint,
   bodega_id bigint,
   nota_credito_id bigint,
   PRIMARY KEY (id)
);