CREATE TABLE nota_debito_compra_linea(
   id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   codigo 	varchar,
   cantidad bigint,
   costo_unitario double precision,
   descuento double precision,
   subtotal_linea double precision,
   iva_linea double precision,
   total_linea double precision,
   entregado varchar,
   fecha_creacion	timestamp without time zone NOT NULL, 
   fecha_actualizacion	timestamp without time zone NOT NULL,
   impuesto_id bigint,
   producto_id bigint,
   bodega_id bigint,
   nota_debito_compra_id bigint,
   PRIMARY KEY (id)
);