CREATE TABLE nota_debito(
   id       bigint IDENTITY NOT NULL,
   codigo 	varchar,
   establecimiento varchar,
   punto_venta varchar,
   secuencial varchar,
   numero_comprobante varchar,
   codigo_numerico varchar,
   clave_acceso varchar,
   fecha timestamp without time zone,
   fecha_autorizacion timestamp without time zone,
   estado varchar,
   proceso_sri varchar,
   descuento double,
   subtotal double,
   subtotal_gravado double,
   subtotal_no_gravado double,
   importe_iva double,
   total double,
   comentario varchar,
   fecha_creacion	timestamp without time zone NOT NULL, 
   fecha_actualizacion	timestamp without time zone NOT NULL,
   factura_id bigint,
   sesion_id bigint,
   tipo_comprobante_id bigint,
   empresa_id bigint,
   PRIMARY KEY (id)
);