CREATE TABLE precio(
   id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   codigo 	varchar,
   costo double precision,
   margen_ganancia double precision,
   precio_sin_iva double precision,
   precio_venta_publico double precision,
   precio_venta_publico_manual double precision,
   utilidad double precision,
   utilidad_porcentaje double precision,
   estado varchar,
   segmento_id bigint,
   producto_id bigint,
   fecha_creacion	timestamp without time zone NOT NULL default CURRENT_TIMESTAMP, 
   fecha_actualizacion	timestamp without time zone NOT NULL default CURRENT_TIMESTAMP,
   PRIMARY KEY (id)
);