CREATE TABLE producto(
   id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   codigo 	varchar,
   nombre varchar,
   consignacion varchar,
   estado varchar,
   fecha_creacion	timestamp without time zone NOT NULL, 
   fecha_actualizacion	timestamp without time zone NOT NULL,
   categoria_producto_id bigint,
   grupo_producto_id bigint,
   tipo_gasto_id bigint,
   impuesto_id bigint,
   medida_id bigint,
   proveedor_id bigint,
   empresa_id bigint,
   PRIMARY KEY (id)
);