CREATE TABLE proveedor(
   id       bigint IDENTITY NOT NULL,
   codigo 	varchar,
   identificacion varchar,
   razon_social varchar,
   nombre_comercial varchar,
   direccion varchar,
   referencia varchar,
   latitudgeo varchar,
   longitudgeo varchar,
   monto_financiamiento double,
   especial varchar,
   obligado_contabilidad varchar,
   fantasma varchar,
   relacionado varchar,
   estado varchar,
   fecha_creacion	timestamp without time zone NOT NULL, 
   fecha_actualizacion	timestamp without time zone NOT NULL,
   tipo_identificacion_id bigint,
   tipo_contribuyente_id bigint,
   grupo_proveedor_id bigint,
   forma_pago_id bigint,
   plazo_credito_id bigint,
   ubicacion_id bigint,
   empresa_id bigint,
   PRIMARY KEY (id)
);