CREATE TABLE sesion(
   id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   codigo 	varchar,
   fecha_apertura timestamp without time zone,
   fecha_cierre timestamp without time zone,
   ip varchar,
   estado varchar,
   usuario_id bigint,
   fecha_creacion	timestamp without time zone NOT NULL default CURRENT_TIMESTAMP, 
   fecha_actualizacion	timestamp without time zone NOT NULL default CURRENT_TIMESTAMP,
   PRIMARY KEY (id)
);