CREATE TABLE tipo_retencion(
   id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   codigo 	varchar,
   impuesto_retencion varchar,
   tipo_retencion varchar,
   codigo_sri varchar,
   descripcion varchar,
   porcentaje double precision,
   estado varchar,
   fecha_creacion	timestamp without time zone NOT NULL default CURRENT_TIMESTAMP, 
   fecha_actualizacion	timestamp without time zone NOT NULL default CURRENT_TIMESTAMP,
   PRIMARY KEY (id)
);