CREATE TABLE transferencia(
   id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   codigo 	varchar,
   fecha timestamp without time zone,
   tipo varchar,
   comprobante varchar,
   valor double precision,
   cuenta_propia_id bigint,
   factura_id bigint,
   fecha_creacion	timestamp without time zone NOT NULL default CURRENT_TIMESTAMP, 
   fecha_actualizacion	timestamp without time zone NOT NULL default CURRENT_TIMESTAMP,
   PRIMARY KEY (id)
);