CREATE TABLE vehiculo(
   id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   codigo 	varchar,
   placa varchar,
   numero varchar,
   marca varchar,
   modelo varchar,
   anio varchar,
   cilindraje varchar,
   clase varchar,
   color varchar,
   fabricacion varchar,
   estado varchar,
   empresa_id bigint,
   fecha_creacion	timestamp without time zone NOT NULL default CURRENT_TIMESTAMP, 
   fecha_actualizacion	timestamp without time zone NOT NULL default CURRENT_TIMESTAMP,
   PRIMARY KEY (id)
);