insert into paquete(id, codigo, nombre, minimo_comprobantes, maximo_comprobantes, valor_total, valor_anual, valor_minimo, valor_maximo, valor_puesta_inicial, porcentaje_comision, comision, cantidad_usuario_recaudacion, cantidad_usuario_gerente, cantidad_usuario_administrador, tipo, estado, fecha_creacion, fecha_actualizacion) values (default, 'PAQ202301000001', 'RANGO 1 MENSUAL', 1, 12, 3.00, 36.00, 3.00, 0.25, 0, 5, 0.15, 2, 1, 0, 'MENSUAL', 'ACTIVO', default, default);
insert into paquete(id, codigo, nombre, minimo_comprobantes, maximo_comprobantes, valor_total, valor_anual, valor_minimo, valor_maximo, valor_puesta_inicial, porcentaje_comision, comision, cantidad_usuario_recaudacion, cantidad_usuario_gerente, cantidad_usuario_administrador, tipo, estado, fecha_creacion, fecha_actualizacion) values (default, 'PAQ202301000002', 'RANGO 2 MENSUAL', 13, 25, 5.99, 71.88, 0.46, 0.24, 0, 10, 0.60, 2, 1, 0, 'MENSUAL', 'ACTIVO', default, default);
insert into paquete(id, codigo, nombre, minimo_comprobantes, maximo_comprobantes, valor_total, valor_anual, valor_minimo, valor_maximo, valor_puesta_inicial, porcentaje_comision, comision, cantidad_usuario_recaudacion, cantidad_usuario_gerente, cantidad_usuario_administrador, tipo, estado, fecha_creacion, fecha_actualizacion) values (default, 'PAQ202301000003', 'RANGO 3 MENSUAL', 26, 50, 9.99, 119.88, 0.38, 0.20, 0, 10, 1.00, 2, 1, 0, 'MENSUAL', 'ACTIVO', default, default);
insert into paquete(id, codigo, nombre, minimo_comprobantes, maximo_comprobantes, valor_total, valor_anual, valor_minimo, valor_maximo, valor_puesta_inicial, porcentaje_comision, comision, cantidad_usuario_recaudacion, cantidad_usuario_gerente, cantidad_usuario_administrador, tipo, estado, fecha_creacion, fecha_actualizacion) values (default, 'PAQ202301000004', 'RANGO 4 MENSUAL', 51, 100, 9.99, 119.88, 0.38, 0.20, 0, 15, 3.00, 2, 1, 0, 'MENSUAL', 'ACTIVO', default, default);
insert into paquete(id, codigo, nombre, minimo_comprobantes, maximo_comprobantes, valor_total, valor_anual, valor_minimo, valor_maximo, valor_puesta_inicial, porcentaje_comision, comision, cantidad_usuario_recaudacion, cantidad_usuario_gerente, cantidad_usuario_administrador, tipo, estado, fecha_creacion, fecha_actualizacion) values (default, 'PAQ202301000005', 'RANGO 5 MENSUAL', 101, 200, 19.99, 239.88, 0.39, 0.20, 0, 15, 6.00, 2, 1, 0, 'MENSUAL', 'ACTIVO', default, default);
insert into paquete(id, codigo, nombre, minimo_comprobantes, maximo_comprobantes, valor_total, valor_anual, valor_minimo, valor_maximo, valor_puesta_inicial, porcentaje_comision, comision, cantidad_usuario_recaudacion, cantidad_usuario_gerente, cantidad_usuario_administrador, tipo, estado, fecha_creacion, fecha_actualizacion) values (default, 'PAQ202301000006', 'RANGO 6 MENSUAL', 201, 500, 64.99, 779.88, 0.32, 0.13, 0, 20, 13.00, 2, 1, 0, 'MENSUAL', 'ACTIVO', default, default);
insert into paquete(id, codigo, nombre, minimo_comprobantes, maximo_comprobantes, valor_total, valor_anual, valor_minimo, valor_maximo, valor_puesta_inicial, porcentaje_comision, comision, cantidad_usuario_recaudacion, cantidad_usuario_gerente, cantidad_usuario_administrador, tipo, estado, fecha_creacion, fecha_actualizacion) values (default, 'PAQ202301000007', 'RANGO 7 MENSUAL', 501, 1000, 79.99, 959.88, 0.16, 0.08, 0, 20, 16.00, 2, 1, 0, 'MENSUAL', 'ACTIVO', default, default);
insert into paquete(id, codigo, nombre, minimo_comprobantes, maximo_comprobantes, valor_total, valor_anual, valor_minimo, valor_maximo, valor_puesta_inicial, porcentaje_comision, comision, cantidad_usuario_recaudacion, cantidad_usuario_gerente, cantidad_usuario_administrador, tipo, estado, fecha_creacion, fecha_actualizacion) values (default, 'PAQ202301000008', 'RANGO 8 MENSUAL', 1001, 10000, 99.99, 1199.88, 0.10, 0.01, 0, 25, 25.00, 2, 1, 0, 'MENSUAL', 'ACTIVO', default, default);

insert into paquete(id, codigo, nombre, minimo_comprobantes, maximo_comprobantes, valor_total, valor_anual, valor_minimo, valor_maximo, valor_puesta_inicial, porcentaje_comision, comision, cantidad_usuario_recaudacion, cantidad_usuario_gerente, cantidad_usuario_administrador, tipo, estado, fecha_creacion, fecha_actualizacion) values (default, 'PAQ202301000009', 'RANGO 1 ANUAL', 1, 12, 12.00, 5.00, 5.00, 0.42, 10.00, 5, 0.25, 1, 0, 0, 'ANUAL', 'ACTIVO', default, default);
insert into paquete(id, codigo, nombre, minimo_comprobantes, maximo_comprobantes, valor_total, valor_anual, valor_minimo, valor_maximo, valor_puesta_inicial, porcentaje_comision, comision, cantidad_usuario_recaudacion, cantidad_usuario_gerente, cantidad_usuario_administrador, tipo, estado, fecha_creacion, fecha_actualizacion) values (default, 'PAQ202301000010', 'RANGO 2 ANUAL', 13, 25, 20.00, 10.00, 0.77, 0.40, 10.00, 10, 1.00, 1, 0, 0, 'ANUAL', 'ACTIVO', default, default);
insert into paquete(id, codigo, nombre, minimo_comprobantes, maximo_comprobantes, valor_total, valor_anual, valor_minimo, valor_maximo, valor_puesta_inicial, porcentaje_comision, comision, cantidad_usuario_recaudacion, cantidad_usuario_gerente, cantidad_usuario_administrador, tipo, estado, fecha_creacion, fecha_actualizacion) values (default, 'PAQ202301000011', 'RANGO 3 ANUAL', 26, 50, 30.00, 20.00, 0.77, 0.40, 10.00, 10, 2.00, 1, 0, 0, 'ANUAL', 'ACTIVO', default, default);
insert into paquete(id, codigo, nombre, minimo_comprobantes, maximo_comprobantes, valor_total, valor_anual, valor_minimo, valor_maximo, valor_puesta_inicial, porcentaje_comision, comision, cantidad_usuario_recaudacion, cantidad_usuario_gerente, cantidad_usuario_administrador, tipo, estado, fecha_creacion, fecha_actualizacion) values (default, 'PAQ202301000012', 'RANGO 4 ANUAL', 51, 100, 45.00, 36.00, 0.71, 0.36, 10.00, 15, 5.40, 1, 0, 0, 'ANUAL', 'ACTIVO', default, default);
insert into paquete(id, codigo, nombre, minimo_comprobantes, maximo_comprobantes, valor_total, valor_anual, valor_minimo, valor_maximo, valor_puesta_inicial, porcentaje_comision, comision, cantidad_usuario_recaudacion, cantidad_usuario_gerente, cantidad_usuario_administrador, tipo, estado, fecha_creacion, fecha_actualizacion) values (default, 'PAQ202301000013', 'RANGO 5 ANUAL', 101, 200, 65.00, 50.00, 0.50, 0.25, 10.00, 15, 7.50, 1, 0, 0, 'ANUAL', 'ACTIVO', default, default);
insert into paquete(id, codigo, nombre, minimo_comprobantes, maximo_comprobantes, valor_total, valor_anual, valor_minimo, valor_maximo, valor_puesta_inicial, porcentaje_comision, comision, cantidad_usuario_recaudacion, cantidad_usuario_gerente, cantidad_usuario_administrador, tipo, estado, fecha_creacion, fecha_actualizacion) values (default, 'PAQ202301000014', 'RANGO 6 ANUAL', 201, 500, 120.00, 100.00, 0.50, 0.20, 10.00, 15, 15.00, 1, 0, 0, 'ANUAL', 'ACTIVO', default, default);
insert into paquete(id, codigo, nombre, minimo_comprobantes, maximo_comprobantes, valor_total, valor_anual, valor_minimo, valor_maximo, valor_puesta_inicial, porcentaje_comision, comision, cantidad_usuario_recaudacion, cantidad_usuario_gerente, cantidad_usuario_administrador, tipo, estado, fecha_creacion, fecha_actualizacion) values (default, 'PAQ202301000015', 'RANGO 7 ANUAL', 501, 1000, 150.00, 120.00, 0.24, 0.12, 10.00, 20, 24.00, 1, 0, 0, 'ANUAL', 'ACTIVO', default, default);
insert into paquete(id, codigo, nombre, minimo_comprobantes, maximo_comprobantes, valor_total, valor_anual, valor_minimo, valor_maximo, valor_puesta_inicial, porcentaje_comision, comision, cantidad_usuario_recaudacion, cantidad_usuario_gerente, cantidad_usuario_administrador, tipo, estado, fecha_creacion, fecha_actualizacion) values (default, 'PAQ202301000016', 'RANGO 8 ANUAL', 1001, 10000, 180.00, 140.00, 0.14, 0.00, 10.00, 25, 35.00, 1, 0, 0, 'ANUAL', 'ACTIVO', default, default);